(cl:defpackage scene_understanding-srv
  (:use )
  (:export
   "SETCOSTMAPAROUNDVEHICLE"
   "<SETCOSTMAPAROUNDVEHICLE-REQUEST>"
   "SETCOSTMAPAROUNDVEHICLE-REQUEST"
   "<SETCOSTMAPAROUNDVEHICLE-RESPONSE>"
   "SETCOSTMAPAROUNDVEHICLE-RESPONSE"
  ))

