// Generated by gencpp from file scene_understanding/GPSHeading.msg
// DO NOT EDIT!


#ifndef SCENE_UNDERSTANDING_MESSAGE_GPSHEADING_H
#define SCENE_UNDERSTANDING_MESSAGE_GPSHEADING_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace scene_understanding
{
template <class ContainerAllocator>
struct GPSHeading_
{
  typedef GPSHeading_<ContainerAllocator> Type;

  GPSHeading_()
    : header()
    , heading_deg(0.0)  {
    }
  GPSHeading_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , heading_deg(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef float _heading_deg_type;
  _heading_deg_type heading_deg;





  typedef boost::shared_ptr< ::scene_understanding::GPSHeading_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::scene_understanding::GPSHeading_<ContainerAllocator> const> ConstPtr;

}; // struct GPSHeading_

typedef ::scene_understanding::GPSHeading_<std::allocator<void> > GPSHeading;

typedef boost::shared_ptr< ::scene_understanding::GPSHeading > GPSHeadingPtr;
typedef boost::shared_ptr< ::scene_understanding::GPSHeading const> GPSHeadingConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::scene_understanding::GPSHeading_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::scene_understanding::GPSHeading_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::scene_understanding::GPSHeading_<ContainerAllocator1> & lhs, const ::scene_understanding::GPSHeading_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.heading_deg == rhs.heading_deg;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::scene_understanding::GPSHeading_<ContainerAllocator1> & lhs, const ::scene_understanding::GPSHeading_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace scene_understanding

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::scene_understanding::GPSHeading_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::scene_understanding::GPSHeading_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::scene_understanding::GPSHeading_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::scene_understanding::GPSHeading_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::scene_understanding::GPSHeading_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::scene_understanding::GPSHeading_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::scene_understanding::GPSHeading_<ContainerAllocator> >
{
  static const char* value()
  {
    return "3cf6fb6acd86d7f29e5238051c7a5ee6";
  }

  static const char* value(const ::scene_understanding::GPSHeading_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x3cf6fb6acd86d7f2ULL;
  static const uint64_t static_value2 = 0x9e5238051c7a5ee6ULL;
};

template<class ContainerAllocator>
struct DataType< ::scene_understanding::GPSHeading_<ContainerAllocator> >
{
  static const char* value()
  {
    return "scene_understanding/GPSHeading";
  }

  static const char* value(const ::scene_understanding::GPSHeading_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::scene_understanding::GPSHeading_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"float32 heading_deg\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::scene_understanding::GPSHeading_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::scene_understanding::GPSHeading_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.heading_deg);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GPSHeading_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::scene_understanding::GPSHeading_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::scene_understanding::GPSHeading_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "heading_deg: ";
    Printer<float>::stream(s, indent + "  ", v.heading_deg);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SCENE_UNDERSTANDING_MESSAGE_GPSHEADING_H
