// Generated by gencpp from file scene_understanding/SetCostMapAroundVehicleRequest.msg
// DO NOT EDIT!


#ifndef SCENE_UNDERSTANDING_MESSAGE_SETCOSTMAPAROUNDVEHICLEREQUEST_H
#define SCENE_UNDERSTANDING_MESSAGE_SETCOSTMAPAROUNDVEHICLEREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace scene_understanding
{
template <class ContainerAllocator>
struct SetCostMapAroundVehicleRequest_
{
  typedef SetCostMapAroundVehicleRequest_<ContainerAllocator> Type;

  SetCostMapAroundVehicleRequest_()
    : height(0.0)
    , width(0.0)
    , cost(0.0)  {
    }
  SetCostMapAroundVehicleRequest_(const ContainerAllocator& _alloc)
    : height(0.0)
    , width(0.0)
    , cost(0.0)  {
  (void)_alloc;
    }



   typedef float _height_type;
  _height_type height;

   typedef float _width_type;
  _width_type width;

   typedef float _cost_type;
  _cost_type cost;





  typedef boost::shared_ptr< ::scene_understanding::SetCostMapAroundVehicleRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::scene_understanding::SetCostMapAroundVehicleRequest_<ContainerAllocator> const> ConstPtr;

}; // struct SetCostMapAroundVehicleRequest_

typedef ::scene_understanding::SetCostMapAroundVehicleRequest_<std::allocator<void> > SetCostMapAroundVehicleRequest;

typedef boost::shared_ptr< ::scene_understanding::SetCostMapAroundVehicleRequest > SetCostMapAroundVehicleRequestPtr;
typedef boost::shared_ptr< ::scene_understanding::SetCostMapAroundVehicleRequest const> SetCostMapAroundVehicleRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::scene_understanding::SetCostMapAroundVehicleRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::scene_understanding::SetCostMapAroundVehicleRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::scene_understanding::SetCostMapAroundVehicleRequest_<ContainerAllocator1> & lhs, const ::scene_understanding::SetCostMapAroundVehicleRequest_<ContainerAllocator2> & rhs)
{
  return lhs.height == rhs.height &&
    lhs.width == rhs.width &&
    lhs.cost == rhs.cost;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::scene_understanding::SetCostMapAroundVehicleRequest_<ContainerAllocator1> & lhs, const ::scene_understanding::SetCostMapAroundVehicleRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace scene_understanding

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::scene_understanding::SetCostMapAroundVehicleRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::scene_understanding::SetCostMapAroundVehicleRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::scene_understanding::SetCostMapAroundVehicleRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::scene_understanding::SetCostMapAroundVehicleRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::scene_understanding::SetCostMapAroundVehicleRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::scene_understanding::SetCostMapAroundVehicleRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::scene_understanding::SetCostMapAroundVehicleRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "fca6d11a516d37ffdf2214caeed4dbb8";
  }

  static const char* value(const ::scene_understanding::SetCostMapAroundVehicleRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xfca6d11a516d37ffULL;
  static const uint64_t static_value2 = 0xdf2214caeed4dbb8ULL;
};

template<class ContainerAllocator>
struct DataType< ::scene_understanding::SetCostMapAroundVehicleRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "scene_understanding/SetCostMapAroundVehicleRequest";
  }

  static const char* value(const ::scene_understanding::SetCostMapAroundVehicleRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::scene_understanding::SetCostMapAroundVehicleRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 height\n"
"float32 width\n"
"float32 cost\n"
;
  }

  static const char* value(const ::scene_understanding::SetCostMapAroundVehicleRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::scene_understanding::SetCostMapAroundVehicleRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.height);
      stream.next(m.width);
      stream.next(m.cost);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SetCostMapAroundVehicleRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::scene_understanding::SetCostMapAroundVehicleRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::scene_understanding::SetCostMapAroundVehicleRequest_<ContainerAllocator>& v)
  {
    s << indent << "height: ";
    Printer<float>::stream(s, indent + "  ", v.height);
    s << indent << "width: ";
    Printer<float>::stream(s, indent + "  ", v.width);
    s << indent << "cost: ";
    Printer<float>::stream(s, indent + "  ", v.cost);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SCENE_UNDERSTANDING_MESSAGE_SETCOSTMAPAROUNDVEHICLEREQUEST_H
