// Generated by gencpp from file scene_understanding/SetCostMapAroundVehicle.msg
// DO NOT EDIT!


#ifndef SCENE_UNDERSTANDING_MESSAGE_SETCOSTMAPAROUNDVEHICLE_H
#define SCENE_UNDERSTANDING_MESSAGE_SETCOSTMAPAROUNDVEHICLE_H

#include <ros/service_traits.h>


#include <scene_understanding/SetCostMapAroundVehicleRequest.h>
#include <scene_understanding/SetCostMapAroundVehicleResponse.h>


namespace scene_understanding
{

struct SetCostMapAroundVehicle
{

typedef SetCostMapAroundVehicleRequest Request;
typedef SetCostMapAroundVehicleResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetCostMapAroundVehicle
} // namespace scene_understanding


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::scene_understanding::SetCostMapAroundVehicle > {
  static const char* value()
  {
    return "8c4553ce63e1ff713460885fc9f3430a";
  }

  static const char* value(const ::scene_understanding::SetCostMapAroundVehicle&) { return value(); }
};

template<>
struct DataType< ::scene_understanding::SetCostMapAroundVehicle > {
  static const char* value()
  {
    return "scene_understanding/SetCostMapAroundVehicle";
  }

  static const char* value(const ::scene_understanding::SetCostMapAroundVehicle&) { return value(); }
};


// service_traits::MD5Sum< ::scene_understanding::SetCostMapAroundVehicleRequest> should match
// service_traits::MD5Sum< ::scene_understanding::SetCostMapAroundVehicle >
template<>
struct MD5Sum< ::scene_understanding::SetCostMapAroundVehicleRequest>
{
  static const char* value()
  {
    return MD5Sum< ::scene_understanding::SetCostMapAroundVehicle >::value();
  }
  static const char* value(const ::scene_understanding::SetCostMapAroundVehicleRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::scene_understanding::SetCostMapAroundVehicleRequest> should match
// service_traits::DataType< ::scene_understanding::SetCostMapAroundVehicle >
template<>
struct DataType< ::scene_understanding::SetCostMapAroundVehicleRequest>
{
  static const char* value()
  {
    return DataType< ::scene_understanding::SetCostMapAroundVehicle >::value();
  }
  static const char* value(const ::scene_understanding::SetCostMapAroundVehicleRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::scene_understanding::SetCostMapAroundVehicleResponse> should match
// service_traits::MD5Sum< ::scene_understanding::SetCostMapAroundVehicle >
template<>
struct MD5Sum< ::scene_understanding::SetCostMapAroundVehicleResponse>
{
  static const char* value()
  {
    return MD5Sum< ::scene_understanding::SetCostMapAroundVehicle >::value();
  }
  static const char* value(const ::scene_understanding::SetCostMapAroundVehicleResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::scene_understanding::SetCostMapAroundVehicleResponse> should match
// service_traits::DataType< ::scene_understanding::SetCostMapAroundVehicle >
template<>
struct DataType< ::scene_understanding::SetCostMapAroundVehicleResponse>
{
  static const char* value()
  {
    return DataType< ::scene_understanding::SetCostMapAroundVehicle >::value();
  }
  static const char* value(const ::scene_understanding::SetCostMapAroundVehicleResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SCENE_UNDERSTANDING_MESSAGE_SETCOSTMAPAROUNDVEHICLE_H
