// Generated by gencpp from file scene_understanding/StereoImagePair_old.msg
// DO NOT EDIT!


#ifndef SCENE_UNDERSTANDING_MESSAGE_STEREOIMAGEPAIR_OLD_H
#define SCENE_UNDERSTANDING_MESSAGE_STEREOIMAGEPAIR_OLD_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <sensor_msgs/Image.h>
#include <sensor_msgs/Image.h>

namespace scene_understanding
{
template <class ContainerAllocator>
struct StereoImagePair_old_
{
  typedef StereoImagePair_old_<ContainerAllocator> Type;

  StereoImagePair_old_()
    : header()
    , leftImage()
    , rightImage()  {
    }
  StereoImagePair_old_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , leftImage(_alloc)
    , rightImage(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef  ::sensor_msgs::Image_<ContainerAllocator>  _leftImage_type;
  _leftImage_type leftImage;

   typedef  ::sensor_msgs::Image_<ContainerAllocator>  _rightImage_type;
  _rightImage_type rightImage;





  typedef boost::shared_ptr< ::scene_understanding::StereoImagePair_old_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::scene_understanding::StereoImagePair_old_<ContainerAllocator> const> ConstPtr;

}; // struct StereoImagePair_old_

typedef ::scene_understanding::StereoImagePair_old_<std::allocator<void> > StereoImagePair_old;

typedef boost::shared_ptr< ::scene_understanding::StereoImagePair_old > StereoImagePair_oldPtr;
typedef boost::shared_ptr< ::scene_understanding::StereoImagePair_old const> StereoImagePair_oldConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::scene_understanding::StereoImagePair_old_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::scene_understanding::StereoImagePair_old_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::scene_understanding::StereoImagePair_old_<ContainerAllocator1> & lhs, const ::scene_understanding::StereoImagePair_old_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.leftImage == rhs.leftImage &&
    lhs.rightImage == rhs.rightImage;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::scene_understanding::StereoImagePair_old_<ContainerAllocator1> & lhs, const ::scene_understanding::StereoImagePair_old_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace scene_understanding

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::scene_understanding::StereoImagePair_old_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::scene_understanding::StereoImagePair_old_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::scene_understanding::StereoImagePair_old_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::scene_understanding::StereoImagePair_old_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::scene_understanding::StereoImagePair_old_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::scene_understanding::StereoImagePair_old_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::scene_understanding::StereoImagePair_old_<ContainerAllocator> >
{
  static const char* value()
  {
    return "2bd638146eaa49b61cb46f08d72754d0";
  }

  static const char* value(const ::scene_understanding::StereoImagePair_old_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x2bd638146eaa49b6ULL;
  static const uint64_t static_value2 = 0x1cb46f08d72754d0ULL;
};

template<class ContainerAllocator>
struct DataType< ::scene_understanding::StereoImagePair_old_<ContainerAllocator> >
{
  static const char* value()
  {
    return "scene_understanding/StereoImagePair_old";
  }

  static const char* value(const ::scene_understanding::StereoImagePair_old_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::scene_understanding::StereoImagePair_old_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"sensor_msgs/Image leftImage\n"
"sensor_msgs/Image rightImage\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: sensor_msgs/Image\n"
"# This message contains an uncompressed image\n"
"# (0, 0) is at top-left corner of image\n"
"#\n"
"\n"
"Header header        # Header timestamp should be acquisition time of image\n"
"                     # Header frame_id should be optical frame of camera\n"
"                     # origin of frame should be optical center of camera\n"
"                     # +x should point to the right in the image\n"
"                     # +y should point down in the image\n"
"                     # +z should point into to plane of the image\n"
"                     # If the frame_id here and the frame_id of the CameraInfo\n"
"                     # message associated with the image conflict\n"
"                     # the behavior is undefined\n"
"\n"
"uint32 height         # image height, that is, number of rows\n"
"uint32 width          # image width, that is, number of columns\n"
"\n"
"# The legal values for encoding are in file src/image_encodings.cpp\n"
"# If you want to standardize a new string format, join\n"
"# ros-users@lists.sourceforge.net and send an email proposing a new encoding.\n"
"\n"
"string encoding       # Encoding of pixels -- channel meaning, ordering, size\n"
"                      # taken from the list of strings in include/sensor_msgs/image_encodings.h\n"
"\n"
"uint8 is_bigendian    # is this data bigendian?\n"
"uint32 step           # Full row length in bytes\n"
"uint8[] data          # actual matrix data, size is (step * rows)\n"
;
  }

  static const char* value(const ::scene_understanding::StereoImagePair_old_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::scene_understanding::StereoImagePair_old_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.leftImage);
      stream.next(m.rightImage);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct StereoImagePair_old_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::scene_understanding::StereoImagePair_old_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::scene_understanding::StereoImagePair_old_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "leftImage: ";
    s << std::endl;
    Printer< ::sensor_msgs::Image_<ContainerAllocator> >::stream(s, indent + "  ", v.leftImage);
    s << indent << "rightImage: ";
    s << std::endl;
    Printer< ::sensor_msgs::Image_<ContainerAllocator> >::stream(s, indent + "  ", v.rightImage);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SCENE_UNDERSTANDING_MESSAGE_STEREOIMAGEPAIR_OLD_H
