// Generated by gencpp from file scene_understanding/VoxelData.msg
// DO NOT EDIT!


#ifndef SCENE_UNDERSTANDING_MESSAGE_VOXELDATA_H
#define SCENE_UNDERSTANDING_MESSAGE_VOXELDATA_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <scene_understanding/VoxelValue.h>

namespace scene_understanding
{
template <class ContainerAllocator>
struct VoxelData_
{
  typedef VoxelData_<ContainerAllocator> Type;

  VoxelData_()
    : header()
    , resolution(0.0)
    , data()  {
    }
  VoxelData_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , resolution(0.0)
    , data(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef double _resolution_type;
  _resolution_type resolution;

   typedef std::vector< ::scene_understanding::VoxelValue_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::scene_understanding::VoxelValue_<ContainerAllocator> >> _data_type;
  _data_type data;





  typedef boost::shared_ptr< ::scene_understanding::VoxelData_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::scene_understanding::VoxelData_<ContainerAllocator> const> ConstPtr;

}; // struct VoxelData_

typedef ::scene_understanding::VoxelData_<std::allocator<void> > VoxelData;

typedef boost::shared_ptr< ::scene_understanding::VoxelData > VoxelDataPtr;
typedef boost::shared_ptr< ::scene_understanding::VoxelData const> VoxelDataConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::scene_understanding::VoxelData_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::scene_understanding::VoxelData_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::scene_understanding::VoxelData_<ContainerAllocator1> & lhs, const ::scene_understanding::VoxelData_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.resolution == rhs.resolution &&
    lhs.data == rhs.data;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::scene_understanding::VoxelData_<ContainerAllocator1> & lhs, const ::scene_understanding::VoxelData_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace scene_understanding

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::scene_understanding::VoxelData_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::scene_understanding::VoxelData_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::scene_understanding::VoxelData_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::scene_understanding::VoxelData_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::scene_understanding::VoxelData_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::scene_understanding::VoxelData_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::scene_understanding::VoxelData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ef47bab6b7887fe67691b47c4525189e";
  }

  static const char* value(const ::scene_understanding::VoxelData_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xef47bab6b7887fe6ULL;
  static const uint64_t static_value2 = 0x7691b47c4525189eULL;
};

template<class ContainerAllocator>
struct DataType< ::scene_understanding::VoxelData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "scene_understanding/VoxelData";
  }

  static const char* value(const ::scene_understanding::VoxelData_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::scene_understanding::VoxelData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"\n"
"float64 resolution # The resolution of the voxel data in meters\n"
"\n"
"VoxelValue[] data  # The list of voxel data. Positions are the center of the voxel\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: scene_understanding/VoxelValue\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"float32 density\n"
"float32 density_confidence\n"
"\n"
"float32 rgb\n"
"\n"
"uint8 material\n"
;
  }

  static const char* value(const ::scene_understanding::VoxelData_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::scene_understanding::VoxelData_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.resolution);
      stream.next(m.data);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct VoxelData_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::scene_understanding::VoxelData_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::scene_understanding::VoxelData_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "resolution: ";
    Printer<double>::stream(s, indent + "  ", v.resolution);
    s << indent << "data[]" << std::endl;
    for (size_t i = 0; i < v.data.size(); ++i)
    {
      s << indent << "  data[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::scene_understanding::VoxelValue_<ContainerAllocator> >::stream(s, indent + "    ", v.data[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // SCENE_UNDERSTANDING_MESSAGE_VOXELDATA_H
