// Generated by gencpp from file lio_sam/save_map.msg
// DO NOT EDIT!


#ifndef LIO_SAM_MESSAGE_SAVE_MAP_H
#define LIO_SAM_MESSAGE_SAVE_MAP_H

#include <ros/service_traits.h>


#include <lio_sam/save_mapRequest.h>
#include <lio_sam/save_mapResponse.h>


namespace lio_sam
{

struct save_map
{

typedef save_mapRequest Request;
typedef save_mapResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct save_map
} // namespace lio_sam


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::lio_sam::save_map > {
  static const char* value()
  {
    return "9b82c64d089149d300598523af304f22";
  }

  static const char* value(const ::lio_sam::save_map&) { return value(); }
};

template<>
struct DataType< ::lio_sam::save_map > {
  static const char* value()
  {
    return "lio_sam/save_map";
  }

  static const char* value(const ::lio_sam::save_map&) { return value(); }
};


// service_traits::MD5Sum< ::lio_sam::save_mapRequest> should match
// service_traits::MD5Sum< ::lio_sam::save_map >
template<>
struct MD5Sum< ::lio_sam::save_mapRequest>
{
  static const char* value()
  {
    return MD5Sum< ::lio_sam::save_map >::value();
  }
  static const char* value(const ::lio_sam::save_mapRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::lio_sam::save_mapRequest> should match
// service_traits::DataType< ::lio_sam::save_map >
template<>
struct DataType< ::lio_sam::save_mapRequest>
{
  static const char* value()
  {
    return DataType< ::lio_sam::save_map >::value();
  }
  static const char* value(const ::lio_sam::save_mapRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::lio_sam::save_mapResponse> should match
// service_traits::MD5Sum< ::lio_sam::save_map >
template<>
struct MD5Sum< ::lio_sam::save_mapResponse>
{
  static const char* value()
  {
    return MD5Sum< ::lio_sam::save_map >::value();
  }
  static const char* value(const ::lio_sam::save_mapResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::lio_sam::save_mapResponse> should match
// service_traits::DataType< ::lio_sam::save_map >
template<>
struct DataType< ::lio_sam::save_mapResponse>
{
  static const char* value()
  {
    return DataType< ::lio_sam::save_map >::value();
  }
  static const char* value(const ::lio_sam::save_mapResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // LIO_SAM_MESSAGE_SAVE_MAP_H
