dataset: "rellis"
save_dir: "Encoder_Rellis"
load_epoch: 1

seed: 42
num_frames: 5
num_workers: 16

debug_mode: False
visualize: False
meas_result: False
gen_preds: False
result_split: "val"

train:
  B: 4
  num_epochs: 5
  lr: 0.007
  motion_weight: 0.0001
  BETA1: 0.9
  BETA2: 0.999
  decayRate: 0.96
  opt: "Adam"
  grid_params:
    grid_size: [ 200.0, 200.0, 26.0 ]
    min_bound: [ -20.0, -20.0, -2.6 ]
    max_bound: [ 20.0, 20.0, 2.6 ]
test:
  grid_params:
    grid_size: [ 200.0, 200.0, 26.0 ]
    min_bound: [ -20.0, -20.0, -2.6 ]
    max_bound: [ 20.0, 20.0, 2.6 ]

