# ROS bag Topics
pc_topic: '/map_pointcloud'
pose_topic: '/map_pose'
publish: False


num_classes: 15

# Conv BKI
grid_size: [300, 300, 50]
min_bound: [-30.0, -30.0, -4]
max_bound: [30.0, 30.0, 6]
voxel_sizes: [0.2, 0.2, 0.2]
f: 5

# Segmentation Net
res: 0.05
cr: 0.5

# Segmentation weights
seg_path: "./weights/Rellis/max-iou-test.pt"

# ConvBKI weights
model_path: "./weights/Rellis/Epoch1.pt"

# rviz color
colors:
  0: [ 108, 64, 20 ] # Dirt
  1: [ 0, 200, 0 ] # Grass
  2: [ 100, 150, 100 ] # Tree
  3: [ 0, 153, 153 ] # Pole
  4: [ 0, 0, 250 ] # Water
  5: [ 255, 255, 0 ] # Vehicle
  6: [ 102, 0, 0 ] # Log
  7: [ 20, 20, 100 ] # Person
  8: [ 110, 22, 22 ] # Fence
  9: [ 40, 120, 20 ] # Bush
  10: [ 110, 22, 22 ] # Concrete
  11: [ 110, 22, 22 ] # Barrier
  12: [ 0, 0, 250 ] # Puddle
  13: [ 99, 66, 34 ] # Mud
  14: [ 110, 22, 22 ] # Rubble
