# ROS bag Topics
pc_topic: '/map_pointcloud'
pose_topic: '/map_pose'
publish: True


num_classes: 15

# Conv BKI
grid_size: [800, 800, 84]
min_bound: [-40.0, -40.0, -4.2]
max_bound: [40.0, 40.0, 4.2]
voxel_sizes: [0.1, 0.1, 0.095]
f: 5

# Segmentation Net
res: 0.05
cr: 0.5

# Segmentation weights
seg_path: "/home/tigeriv/Code/NuScenesConvBKI/spvnas/runs/rellis/checkpoints/max-iou-test.pt"

# ConvBKI weights
model_path: "/home/tigeriv/Code/NuScenesConvBKI/Baselines/Models/Weights/ConvBKIRellis/Epoch1.pt"

# rviz color
colors:
  0: [ 108, 64, 20 ] # Dirt
  1: [ 0, 200, 0 ] # Grass
  2: [ 100, 150, 100 ] # Tree
  3: [ 0, 153, 153 ] # Pole
  4: [ 0, 0, 250 ] # Water
  5: [ 255, 255, 0 ] # Vehicle
  6: [ 102, 0, 0 ] # Log
  7: [ 20, 20, 100 ] # Person
  8: [ 110, 22, 22 ] # Fence
  9: [ 40, 120, 20 ] # Bush
  10: [ 110, 22, 22 ] # Concrete
  11: [ 110, 22, 22 ] # Barrier
  12: [ 0, 0, 250 ] # Puddle
  13: [ 99, 66, 34 ] # Mud
  14: [ 110, 22, 22 ] # Rubble
