# ROS bag Topics
pc_topic: '/map_pointcloud'
pose_topic: '/map_pose' 


num_classes: 15

# Conv BKI
grid_size: [512, 512, 48]
min_bound: [-51.2, -51.2, -6.4]
max_bound: [51.2, 51.2, 3.4]
voxel_sizes: [0.2, 0.2, 0.2]
f: 5

# Segmentation Net
res: 0.05
cr: 0.5

# Segmentation weights
seg_path: "./weights/Rellis/max-iou-test.pt"

# ConvBKI weights
model_path: "./weights/Rellis/Epoch1.pt"

# rviz color
colors:
  0: [ 108, 64, 20 ] # Dirt
  1: [ 0, 102, 0 ] # Grass
  2: [ 200, 200, 0 ] # Tree
  3: [ 0, 153, 153 ] # Pole
  4: [ 0, 128, 200 ] # Water
  5: [ 50, 0, 100 ] # Vehicle
  6: [ 100, 100, 0 ] # Log
  7: [ 200, 0, 127 ] # Person
  8: [ 64, 64, 64 ] # Fence
  9: [ 0, 200, 0 ] # Bush
  10: [ 102, 0, 0 ] # Concrete
  11: [ 204, 153, 254 ] # Barrier
  12: [ 102, 0, 204 ] # Puddle
  13: [ 200, 153, 204 ] # Mud
  14: [ 170, 170, 170 ] # Rubble
