// Generated by gencpp from file liorf/save_map.msg
// DO NOT EDIT!


#ifndef LIORF_MESSAGE_SAVE_MAP_H
#define LIORF_MESSAGE_SAVE_MAP_H

#include <ros/service_traits.h>


#include <liorf/save_mapRequest.h>
#include <liorf/save_mapResponse.h>


namespace liorf
{

struct save_map
{

typedef save_mapRequest Request;
typedef save_mapResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct save_map
} // namespace liorf


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::liorf::save_map > {
  static const char* value()
  {
    return "9b82c64d089149d300598523af304f22";
  }

  static const char* value(const ::liorf::save_map&) { return value(); }
};

template<>
struct DataType< ::liorf::save_map > {
  static const char* value()
  {
    return "liorf/save_map";
  }

  static const char* value(const ::liorf::save_map&) { return value(); }
};


// service_traits::MD5Sum< ::liorf::save_mapRequest> should match
// service_traits::MD5Sum< ::liorf::save_map >
template<>
struct MD5Sum< ::liorf::save_mapRequest>
{
  static const char* value()
  {
    return MD5Sum< ::liorf::save_map >::value();
  }
  static const char* value(const ::liorf::save_mapRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::liorf::save_mapRequest> should match
// service_traits::DataType< ::liorf::save_map >
template<>
struct DataType< ::liorf::save_mapRequest>
{
  static const char* value()
  {
    return DataType< ::liorf::save_map >::value();
  }
  static const char* value(const ::liorf::save_mapRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::liorf::save_mapResponse> should match
// service_traits::MD5Sum< ::liorf::save_map >
template<>
struct MD5Sum< ::liorf::save_mapResponse>
{
  static const char* value()
  {
    return MD5Sum< ::liorf::save_map >::value();
  }
  static const char* value(const ::liorf::save_mapResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::liorf::save_mapResponse> should match
// service_traits::DataType< ::liorf::save_map >
template<>
struct DataType< ::liorf::save_mapResponse>
{
  static const char* value()
  {
    return DataType< ::liorf::save_map >::value();
  }
  static const char* value(const ::liorf::save_mapResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // LIORF_MESSAGE_SAVE_MAP_H
