// Generated by gencpp from file scene_understanding/FusedCostMapMsg.msg
// DO NOT EDIT!


#ifndef SCENE_UNDERSTANDING_MESSAGE_FUSEDCOSTMAPMSG_H
#define SCENE_UNDERSTANDING_MESSAGE_FUSEDCOSTMAPMSG_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <scene_understanding/MapHeader.h>
#include <std_msgs/String.h>

namespace scene_understanding
{
template <class ContainerAllocator>
struct FusedCostMapMsg_
{
  typedef FusedCostMapMsg_<ContainerAllocator> Type;

  FusedCostMapMsg_()
    : mapheader()
    , uuid()
    , xc(0.0)
    , yc(0.0)
    , cost()
    , weight()
    , num_ground_points()
    , num_obstacle_points()
    , ground_elevation()
    , ground_elevation_confidence()
    , updated_cells()  {
    }
  FusedCostMapMsg_(const ContainerAllocator& _alloc)
    : mapheader(_alloc)
    , uuid(_alloc)
    , xc(0.0)
    , yc(0.0)
    , cost(_alloc)
    , weight(_alloc)
    , num_ground_points(_alloc)
    , num_obstacle_points(_alloc)
    , ground_elevation(_alloc)
    , ground_elevation_confidence(_alloc)
    , updated_cells(_alloc)  {
  (void)_alloc;
    }



   typedef  ::scene_understanding::MapHeader_<ContainerAllocator>  _mapheader_type;
  _mapheader_type mapheader;

   typedef  ::std_msgs::String_<ContainerAllocator>  _uuid_type;
  _uuid_type uuid;

   typedef double _xc_type;
  _xc_type xc;

   typedef double _yc_type;
  _yc_type yc;

   typedef std::vector<double, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<double>> _cost_type;
  _cost_type cost;

   typedef std::vector<double, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<double>> _weight_type;
  _weight_type weight;

   typedef std::vector<double, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<double>> _num_ground_points_type;
  _num_ground_points_type num_ground_points;

   typedef std::vector<double, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<double>> _num_obstacle_points_type;
  _num_obstacle_points_type num_obstacle_points;

   typedef std::vector<double, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<double>> _ground_elevation_type;
  _ground_elevation_type ground_elevation;

   typedef std::vector<double, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<double>> _ground_elevation_confidence_type;
  _ground_elevation_confidence_type ground_elevation_confidence;

   typedef std::vector<int8_t, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<int8_t>> _updated_cells_type;
  _updated_cells_type updated_cells;





  typedef boost::shared_ptr< ::scene_understanding::FusedCostMapMsg_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::scene_understanding::FusedCostMapMsg_<ContainerAllocator> const> ConstPtr;

}; // struct FusedCostMapMsg_

typedef ::scene_understanding::FusedCostMapMsg_<std::allocator<void> > FusedCostMapMsg;

typedef boost::shared_ptr< ::scene_understanding::FusedCostMapMsg > FusedCostMapMsgPtr;
typedef boost::shared_ptr< ::scene_understanding::FusedCostMapMsg const> FusedCostMapMsgConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::scene_understanding::FusedCostMapMsg_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::scene_understanding::FusedCostMapMsg_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::scene_understanding::FusedCostMapMsg_<ContainerAllocator1> & lhs, const ::scene_understanding::FusedCostMapMsg_<ContainerAllocator2> & rhs)
{
  return lhs.mapheader == rhs.mapheader &&
    lhs.uuid == rhs.uuid &&
    lhs.xc == rhs.xc &&
    lhs.yc == rhs.yc &&
    lhs.cost == rhs.cost &&
    lhs.weight == rhs.weight &&
    lhs.num_ground_points == rhs.num_ground_points &&
    lhs.num_obstacle_points == rhs.num_obstacle_points &&
    lhs.ground_elevation == rhs.ground_elevation &&
    lhs.ground_elevation_confidence == rhs.ground_elevation_confidence &&
    lhs.updated_cells == rhs.updated_cells;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::scene_understanding::FusedCostMapMsg_<ContainerAllocator1> & lhs, const ::scene_understanding::FusedCostMapMsg_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace scene_understanding

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::scene_understanding::FusedCostMapMsg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::scene_understanding::FusedCostMapMsg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::scene_understanding::FusedCostMapMsg_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::scene_understanding::FusedCostMapMsg_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::scene_understanding::FusedCostMapMsg_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::scene_understanding::FusedCostMapMsg_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::scene_understanding::FusedCostMapMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "7ecf15e3087d12c28ef312a1e88c8e1f";
  }

  static const char* value(const ::scene_understanding::FusedCostMapMsg_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x7ecf15e3087d12c2ULL;
  static const uint64_t static_value2 = 0x8ef312a1e88c8e1fULL;
};

template<class ContainerAllocator>
struct DataType< ::scene_understanding::FusedCostMapMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "scene_understanding/FusedCostMapMsg";
  }

  static const char* value(const ::scene_understanding::FusedCostMapMsg_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::scene_understanding::FusedCostMapMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# This type is a DTO for the uxi_costmap/FusedCostmap type. The members here\n"
"# should be able to exactly mimic the class's internal structure, without loss\n"
"# of information\n"
"\n"
"scene_understanding/MapHeader mapheader\n"
"std_msgs/String     uuid\n"
"\n"
"# Look at the FusedCostMap class for a definition on what this means\n"
"float64 xc\n"
"float64 yc\n"
"\n"
"# All of these maps are stored in column major format.\n"
"float64[] cost\n"
"float64[] weight\n"
"# guassian_weights is not included.\n"
"float64[] num_ground_points\n"
"float64[] num_obstacle_points\n"
"float64[] ground_elevation\n"
"float64[] ground_elevation_confidence\n"
"int8[]    updated_cells\n"
"\n"
"================================================================================\n"
"MSG: scene_understanding/MapHeader\n"
"Header header\n"
"\n"
"float64 originx\n"
"float64 originy\n"
"\n"
"int32 num_rows\n"
"int32 num_cols\n"
"float64 cell_size\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/String\n"
"string data\n"
;
  }

  static const char* value(const ::scene_understanding::FusedCostMapMsg_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::scene_understanding::FusedCostMapMsg_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.mapheader);
      stream.next(m.uuid);
      stream.next(m.xc);
      stream.next(m.yc);
      stream.next(m.cost);
      stream.next(m.weight);
      stream.next(m.num_ground_points);
      stream.next(m.num_obstacle_points);
      stream.next(m.ground_elevation);
      stream.next(m.ground_elevation_confidence);
      stream.next(m.updated_cells);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct FusedCostMapMsg_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::scene_understanding::FusedCostMapMsg_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::scene_understanding::FusedCostMapMsg_<ContainerAllocator>& v)
  {
    s << indent << "mapheader: ";
    s << std::endl;
    Printer< ::scene_understanding::MapHeader_<ContainerAllocator> >::stream(s, indent + "  ", v.mapheader);
    s << indent << "uuid: ";
    s << std::endl;
    Printer< ::std_msgs::String_<ContainerAllocator> >::stream(s, indent + "  ", v.uuid);
    s << indent << "xc: ";
    Printer<double>::stream(s, indent + "  ", v.xc);
    s << indent << "yc: ";
    Printer<double>::stream(s, indent + "  ", v.yc);
    s << indent << "cost[]" << std::endl;
    for (size_t i = 0; i < v.cost.size(); ++i)
    {
      s << indent << "  cost[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.cost[i]);
    }
    s << indent << "weight[]" << std::endl;
    for (size_t i = 0; i < v.weight.size(); ++i)
    {
      s << indent << "  weight[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.weight[i]);
    }
    s << indent << "num_ground_points[]" << std::endl;
    for (size_t i = 0; i < v.num_ground_points.size(); ++i)
    {
      s << indent << "  num_ground_points[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.num_ground_points[i]);
    }
    s << indent << "num_obstacle_points[]" << std::endl;
    for (size_t i = 0; i < v.num_obstacle_points.size(); ++i)
    {
      s << indent << "  num_obstacle_points[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.num_obstacle_points[i]);
    }
    s << indent << "ground_elevation[]" << std::endl;
    for (size_t i = 0; i < v.ground_elevation.size(); ++i)
    {
      s << indent << "  ground_elevation[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.ground_elevation[i]);
    }
    s << indent << "ground_elevation_confidence[]" << std::endl;
    for (size_t i = 0; i < v.ground_elevation_confidence.size(); ++i)
    {
      s << indent << "  ground_elevation_confidence[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.ground_elevation_confidence[i]);
    }
    s << indent << "updated_cells[]" << std::endl;
    for (size_t i = 0; i < v.updated_cells.size(); ++i)
    {
      s << indent << "  updated_cells[" << i << "]: ";
      Printer<int8_t>::stream(s, indent + "  ", v.updated_cells[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // SCENE_UNDERSTANDING_MESSAGE_FUSEDCOSTMAPMSG_H
