// Generated by gencpp from file scene_understanding/WheelEncoderData.msg
// DO NOT EDIT!


#ifndef SCENE_UNDERSTANDING_MESSAGE_WHEELENCODERDATA_H
#define SCENE_UNDERSTANDING_MESSAGE_WHEELENCODERDATA_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace scene_understanding
{
template <class ContainerAllocator>
struct WheelEncoderData_
{
  typedef WheelEncoderData_<ContainerAllocator> Type;

  WheelEncoderData_()
    : header()
    , distance(0.0)
    , velocity(0.0)  {
    }
  WheelEncoderData_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , distance(0.0)
    , velocity(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef double _distance_type;
  _distance_type distance;

   typedef double _velocity_type;
  _velocity_type velocity;





  typedef boost::shared_ptr< ::scene_understanding::WheelEncoderData_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::scene_understanding::WheelEncoderData_<ContainerAllocator> const> ConstPtr;

}; // struct WheelEncoderData_

typedef ::scene_understanding::WheelEncoderData_<std::allocator<void> > WheelEncoderData;

typedef boost::shared_ptr< ::scene_understanding::WheelEncoderData > WheelEncoderDataPtr;
typedef boost::shared_ptr< ::scene_understanding::WheelEncoderData const> WheelEncoderDataConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::scene_understanding::WheelEncoderData_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::scene_understanding::WheelEncoderData_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::scene_understanding::WheelEncoderData_<ContainerAllocator1> & lhs, const ::scene_understanding::WheelEncoderData_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.distance == rhs.distance &&
    lhs.velocity == rhs.velocity;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::scene_understanding::WheelEncoderData_<ContainerAllocator1> & lhs, const ::scene_understanding::WheelEncoderData_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace scene_understanding

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::scene_understanding::WheelEncoderData_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::scene_understanding::WheelEncoderData_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::scene_understanding::WheelEncoderData_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::scene_understanding::WheelEncoderData_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::scene_understanding::WheelEncoderData_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::scene_understanding::WheelEncoderData_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::scene_understanding::WheelEncoderData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "9619d558d5e225001aea81c89858a324";
  }

  static const char* value(const ::scene_understanding::WheelEncoderData_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x9619d558d5e22500ULL;
  static const uint64_t static_value2 = 0x1aea81c89858a324ULL;
};

template<class ContainerAllocator>
struct DataType< ::scene_understanding::WheelEncoderData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "scene_understanding/WheelEncoderData";
  }

  static const char* value(const ::scene_understanding::WheelEncoderData_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::scene_understanding::WheelEncoderData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"# Distance traveled in meters\n"
"float64 distance\n"
"\n"
"# Velocity in meters / second\n"
"float64 velocity\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::scene_understanding::WheelEncoderData_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::scene_understanding::WheelEncoderData_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.distance);
      stream.next(m.velocity);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct WheelEncoderData_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::scene_understanding::WheelEncoderData_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::scene_understanding::WheelEncoderData_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "distance: ";
    Printer<double>::stream(s, indent + "  ", v.distance);
    s << indent << "velocity: ";
    Printer<double>::stream(s, indent + "  ", v.velocity);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SCENE_UNDERSTANDING_MESSAGE_WHEELENCODERDATA_H
